// Copyright 2023-2026 Ant Investor Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/v1/money.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Money represents an amount of money with its currency type.
//
// Field numbers and types intentionally mirror google.type.Money so the
// wire format is identical — services that previously embedded
// google.type.Money can switch to common.v1.Money without coordinating
// deploys with their callers.
type Money struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The 3-letter ISO 4217 currency code (e.g. "KES", "USD", "EUR").
	CurrencyCode string `protobuf:"bytes,1,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	// The whole units of the amount. For example, if currency_code is "USD",
	// 1 unit is one US dollar.
	Units int64 `protobuf:"varint,2,opt,name=units,proto3" json:"units,omitempty"`
	// Number of nano (10^-9) units of the amount. The value must be between
	// -999,999,999 and +999,999,999 inclusive.
	//
	// Sign rules:
	//   - If units is positive, nanos must be positive or zero.
	//   - If units is zero, nanos can be positive, zero, or negative.
	//   - If units is negative, nanos must be negative or zero.
	//
	// For example $-1.75 is represented as units=-1 and nanos=-750,000,000.
	Nanos         int32 `protobuf:"varint,3,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_common_v1_money_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_money_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_common_v1_money_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *Money) GetUnits() int64 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *Money) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

var File_common_v1_money_proto protoreflect.FileDescriptor

const file_common_v1_money_proto_rawDesc = "" +
	"\n" +
	"\x15common/v1/money.proto\x12\tcommon.v1\"X\n" +
	"\x05Money\x12#\n" +
	"\rcurrency_code\x18\x01 \x01(\tR\fcurrencyCode\x12\x14\n" +
	"\x05units\x18\x02 \x01(\x03R\x05units\x12\x14\n" +
	"\x05nanos\x18\x03 \x01(\x05R\x05nanosB:\n" +
	"\bcommonv1P\x01Z)github.com/antinvestor/common/v1;commonv1\xf8\x01\x01b\x06proto3"

var (
	file_common_v1_money_proto_rawDescOnce sync.Once
	file_common_v1_money_proto_rawDescData []byte
)

func file_common_v1_money_proto_rawDescGZIP() []byte {
	file_common_v1_money_proto_rawDescOnce.Do(func() {
		file_common_v1_money_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_money_proto_rawDesc), len(file_common_v1_money_proto_rawDesc)))
	})
	return file_common_v1_money_proto_rawDescData
}

var file_common_v1_money_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_v1_money_proto_goTypes = []any{
	(*Money)(nil), // 0: common.v1.Money
}
var file_common_v1_money_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_money_proto_init() }
func file_common_v1_money_proto_init() {
	if File_common_v1_money_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_money_proto_rawDesc), len(file_common_v1_money_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_money_proto_goTypes,
		DependencyIndexes: file_common_v1_money_proto_depIdxs,
		MessageInfos:      file_common_v1_money_proto_msgTypes,
	}.Build()
	File_common_v1_money_proto = out.File
	file_common_v1_money_proto_goTypes = nil
	file_common_v1_money_proto_depIdxs = nil
}
